export declare const abs: (x: number) => number;
export declare const acos: (x: number) => number;
export declare const asin: (x: number) => number;
export declare const atan: (x: number) => number;
export declare const atan2: (y: number, x: number) => number;
export declare const ceil: (x: number) => number;
export declare const cos: (x: number) => number;
export declare const cosh: (x: number) => number;
export declare function deg(x: number): number;
export declare const exp: (x: number) => number;
export declare const floor: (x: number) => number;
export declare function fmod(x: number, y: number): number;
export declare const huge: number;
export declare const log: (x: number) => number;
export declare const log10: (x: number) => number;
export declare const max: (...values: number[]) => number;
export declare const min: (...values: number[]) => number;
export declare const pi: number;
export declare const nan: number;
export declare const pow: (x: number, y: number) => number;
